# Generated by Django 5.2.4 on 2025-07-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='proficiency',
            field=models.IntegerField(default=0, help_text='Proficiency level from 0-100'),
        ),
    ]
