# Generated by Django 5.2 on 2025-12-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='proficiency',
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(default='', max_length=10),
        ),
    ]
