# Generated by Django 5.2 on 2025-12-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_skill_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='duration',
        ),
        migrations.AddField(
            model_name='experience',
            name='end_date',
            field=models.CharField(default='Present', max_length=100),
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
