# Generated by Django 5.2 on 2025-12-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_project_options_project_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-order', '-id']},
        ),
        migrations.AddField(
            model_name='profile',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0, help_text='Higher numbers appear first'),
        ),
    ]
