# Generated by Django 5.2 on 2025-12-31 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_achievement_options_alter_profile_about_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
